id: PF07B7735
initial_creation_type: input
source_metadata:
  title: Katok Rigdzin Chenpo
  language: de
  description: 'Texts by Katok Rigdzin Chenpo Pema Wangchen Dorje (kaḥ thog rig ''dzin
    chen po padma dbang chen rdo rje):'
  volume:
    b376adff20b0435fbaf00583825546d0:
      title: Prayer for the Long Life of Alak Zenkar Rinpoche, the Incarnation of
        Do Khyentsé Yeshé Dorjé
      parent: Long Life Prayers
    7f0882a6eca44e64a53495c36a23ae67:
      title: Prayer for the Long Life of Pewar Rinpoche
      parent: Long Life Prayers
created_at: '2022-03-01T00:14:41.833937'
last_modified_at: '2022-03-01T00:14:41.833941'
